In [21]:
import numpy as np

In [2]:
myarr = np.array([3,5,6,7]) 

In [3]:
myarr

array([3, 5, 6, 7])

In [ ]:
# taking a break today

### Conversion from other python structure

In [9]:
listarray = np.array([[1,2,3], [5,8,5]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5]])

In [11]:
listarray.shape

(2, 3)

### zeros

In [16]:
zeros = np.zeros((2,5)) # establish zero col/row

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rang = np.arange(15)

In [19]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
rang.shape

(15,)

### linear space

In [48]:
lspace = np.linspace(5,20,4) # start, stop, step 

In [35]:
lspace

array([ 5., 10., 15., 20.])

In [36]:
ide = np.identity(3)

In [37]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
rand = np.empty((5,2))

In [52]:
rand

array([[ 1.        ,  3.11111111],
       [ 5.22222222,  7.33333333],
       [ 9.44444444, 11.55555556],
       [13.66666667, 15.77777778],
       [17.88888889, 20.        ]])

In [57]:
arr = np.arange(95)

In [54]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.reshape(5,19) # change the array dim

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75],
       [76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
        92, 93, 94]])

In [61]:
arr.ravel() # makes 1d array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

## Numpy Axis

![Image Description](numpy_axis.png)
